name: Python App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: "Ticketing Tool"
        run: |
          python -m pip install --upgrade pip
          pip install -r "C:\Users\mbergeron\OneDrive - StorageVault Canada Inc (1)\3.  Workforce Management\Mike Files\Power BI Files\Power Automate Schedule Files\Ticketing Tool\requirements.txt"

      - name: Run Streamlit app (optional)
        run: |
          streamlit run Ticketing\ Tool/wfm_ticket_portal.py --server.headless true
